name: "Build and test"
on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - run: |
        npm install
        npm run build
        npm run test